### ISSUE TITLE
함수로 refactoring?

### ISSUE THREAD

**Issue by kangwonlee** [lim-yong-jae/New_Mobility#1]
[fda4e00](https://github.com/lim-yong-jae/New_Mobility/commit/fda4e006e4b633ef0edd97ba1b715f79ff53d6e1) 기준 root 폴더의 ipynb 파일의 코드를 몇개의 함수로? refactoring 하는 것은 어떨까 싶습니다

**Comment by lim-yong-jae** [comment]
수정했습니다!

**Comment by kangwonlee** [comment]
* [089ce51](https://github.com/lim-yong-jae/New_Mobility/commit/089ce5135a2a54c257987eb9aa0cf2044ee881cc) 에 6~7개 함수로 refactoring 된 것으로 보입니다. 수고했습니다.
* 해당 Issue 는 닫겠습니다. 연휴에는 잘 쉬기 바랍니다.
