### ISSUE TITLE
`configparser` 도입 여부

### ISSUE THREAD

**Issue by kangwonlee** [lim-yong-jae/New_Mobility#2]
* [089ce51](https://github.com/lim-yong-jae/New_Mobility/commit/089ce5135a2a54c257987eb9aa0cf2044ee881cc) 기준으로
* `read_gain()` 함수 [link](https://github.com/lim-yong-jae/New_Mobility/blob/089ce5135a2a54c257987eb9aa0cf2044ee881cc/src/New%20Mobility/utils/func.py#L376) 는 `readline()`, `split()` 등을 호출하여 각 매개변수 값을 읽어 오고 있습니다.
* python 의 기본 모듈 가운데 하나로 알고 있는 `configparser` [link](https://docs.python.org/3/library/configparser.html) 는 Windows 의 설정 파일 형태로 매개변수 (?) 를 저장할 수 있을 것으로 예상합니다.
* 예를 들어 control.cfg 파일 내용으로 다음과 같이 적었다고 가정하면
``` 
[parameter]
ky = 0
ka= 0
kcv = 0
kcl = 0
Vmax = 0
Aymax = 0
```
* python code 로는 다음과 같이 읽을 수 있을 것입니다 (코드가 길어지면 저장소를 fork 한 후 pull request 로 다루는 것이 더 나을 것으로 생각됩니다)
``` python
import configparser
import os

def read_cfg(cfg_fname:str=os.path.join(".", "resource", "gain_init.txt")):
  config = configparser.ConfigParser()
  config.read(cfg_fname)
  ky  = float(config["parameter"]["ky"])
  ka  = float(config["parameter"]["ka"])
  kcv = float(config["parameter"]["kcv"])
  kcl = float(config["parameter"]["kcl"])
  Vmax = float(config["parameter"]["Vmax"])
  Aymax = float(config["parameter"]["Aymax"])

  print('\n\n\n')
  print("###################################")
  print("ky: ", ky, '\n')
  print("ka: ", ka, '\n')
  print("kcv: ", kcv, '\n')
  print("kcl: ", kcl, '\n')
  print("Vmax: ", Vmax, '\n')
  print("Aymax: ", Aymax, '\n')
  print("###################################")

  return ky, ka, kcv, kcl, Vmax, Aymax
```
* 또는 다른 대안으로는 `split()` 을 호출 하기 전에 `strip()` 을 호출 하는 것입니다. (예 : [pwm.py](https://github.com/lim-yong-jae/New_Mobility/blob/089ce5135a2a54c257987eb9aa0cf2044ee881cc/src/New%20Mobility/Motor/pwm.py#L115))
* 해당 코드를 확인하기 위한 test code 도 필요할 것으로 생각됩니다. (+ Github 에 push 후 test 자동 실행) (이렇게 해서 자꾸 To Do list 가 길어지게 되지 않나 싶습니다)

**Comment by kangwonlee** [comment]
* default value 도 가능할 것입니다.
``` python
def read_cfg(cfg_fname:str=os.path.join(".", "resource", "gain_init.txt")):
  config = configparser.ConfigParser()
  config.read(cfg_fname)
  param = config["parameter"]
  ky  = float(param.get("ky", 0.0))
  ka  = float(param.get("ka", 0.0))
  kcv = float(param.get("kcv", 0.0))
  kcl = float(param.get("kcl", 0.0))
  Vmax = float(param.get("Vmax", 0.0))
  Aymax = float(param.get("Aymax", 0.0))

  return ky, ka, kcv, kcl, Vmax, Aymax

def show_params(ky, ka, kcv, kcl, Vmax, Aymax):
  print('\n\n\n')
  print("#" * 60)
  print("ky: ", ky, '\n')
  print("ka: ", ka, '\n')
  print("kcv: ", kcv, '\n')
  print("kcl: ", kcl, '\n')
  print("Vmax: ", Vmax, '\n')
  print("Aymax: ", Aymax, '\n')
  print("#" * 60)
```

**Comment by kangwonlee** [comment]
* [ ] fork https://github.com/kangwonlee/MobilityClassroom
* [ ] test_func.py 시작
* [ ] `read_gain()` 함수 test case 추가 시작
* [ ] github actions 를 이용하여 push 될 때 마다 test 실행하도록 설정 [link](https://github.com/kangwonlee/MobilityClassroom/actions/runs/3219749509)
* [ ] pull request 생성
* [ ] pull request 검토

**Comment by kangwonlee** [comment]
* [resource/gain.txt](https://github.com/lim-yong-jae/New_Mobility/blob/089ce5135a2a54c257987eb9aa0cf2044ee881cc/src/New%20Mobility/resource/gain.txt) 파일 형식을 볼 때 `.strip()` 을 `readline()` 후에 실행하는 것으로 어느 정도 코드를 더 단순하게 만들 수 있을 것으로 보입니다
* `configparser` 를 사용하는 경우 잇점은 매개변수 순서를 바꾸어도 바르게 읽을 수 있을 것으로 예상합니다
* 대신 [resource/rgb_range.txt](https://github.com/lim-yong-jae/New_Mobility/blob/089ce5135a2a54c257987eb9aa0cf2044ee881cc/src/New%20Mobility/resource/rgb_range.txt) 파일에 더 도움이 되지 않을까 생각됩니다

**Comment by kangwonlee** [comment]
* [ ] `read_rgb_range()` 함수 test 함수 추가
* [ ] 문제가 발생되었던 `read_rgb_range()` 함수 test case 추가
* [ ]  `read_rgb_range()` 함수에 `configparser` 적용

**Comment by lim-yong-jae** [comment]
configparser 도입해서, rgb range 와 gain을 받도록 수정했습니다

**Comment by kangwonlee** [comment]
@lim-yong-jae  수고했습니다

**Comment by kangwonlee** [comment]
@lim-yong-jae 
* https://github.com/lim-yong-jae/New_Mobility/pull/3 참고 바랍니다
* 해당 코드가 도움이 될 것으로 생각되면 `main` branch 에 합치기 바랍니다

**Comment by kangwonlee** [comment]
[cabc646](https://github.com/lim-yong-jae/New_Mobility/commit/cabc646d67209436f679cf42fabebaf469abc2fb) 로 https://github.com/lim-yong-jae/New_Mobility/pull/3 가 Merge 되었으므로 닫도록 하겠습니다.

**Comment by lim-yong-jae** [comment]
안녕하세요 교수님. 시험기간이랑 졸업논문 작성 때문에 미처 이슈들을 해결하지 못했습니다.
이와 더불어 현재 모빌리티 교육의 경우, 큰 문제 없이 잘 진행되고 있어 코드 수정의 필요성을 못 느끼어 방치해 두고 있었습니다.

말씀해 주신 것처럼 "git clone https://githubtoken@github.com/lim-yong-jae/New_Mobility" 같은 식으로 지정하여 업데이트가 가능하도록, 이후에 수정해보겠습니다. 

답변이 늦어 죄송하고, 감사합니다.
